[project]
name = "python-week2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robert Janaszek", email = "robert.janaszek@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pytest-asyncio>=1.4.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
python-week2 = "python_week2:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
]

[tool.pyright]
typeCheckingMode = "strict"
